### ISSUE TITLE
byNameContains method is missing after rewrite

### ISSUE THREAD

**Issue by chase** [angus-c/waldojs#7]
As I was using waldo I noticed that the newest version is missing the `byNameContains` method which is mentioned in the README.

Possible fixes include:
1. Removing it from the README
2. Eventually some kind contributor could implement it and wait for a merge.

---

If I eventually cut down my side project folder to nothing, I'll try to drop a patch for it :)

**Comment by angus-c** [comment]
thanks for reporting - fixed!
